name: Build Markdown to HTML

on:
  push:
    paths:
      - "src/**"
      - "assets/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Build pages
        run: |
          HEADER="$(cat src/templates/header.html)"
          FOOTER="$(cat src/templates/footer.html)"

          for file in src/md/*.md; do
            NAME=$(basename "$file" .md)
            pandoc "$file" \
              --template=src/templates/page.html \
              --metadata title="$NAME" \
              --metadata hero="assets/images/hero-$NAME.jpg" \
              --metadata header="$HEADER" \
              --metadata footer="$FOOTER" \
              --output "$NAME.html"
          done

      - name: Commit HTML
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add *.html
          git commit -m "Auto-build HTML" || echo "No changes"
          git push

